# Header
menu:
  主页: /
  归档: /archives/
  GitHub: https://github.com/Chion82
  About Me: /about.html
rss: /atom.xml

themes:
  uzume:
    img: /images/theme_uzume.png
    css: /css/style.css
  miria:
    img: /images/theme_miria.png
    css: /stylesheets/theme_miria.css

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
